const resList = [
  {
    id: "101059",
    name: "Manohar Dairy and Restaurant",
    cloudinaryImageId: "yhnrql8wxgu8sgqjczos",
    locality: "Hamidia Road",
    areaName: "Hamidia Road",
    costForTwo: "₹300 for two",
    cuisines: [
      "Sweets",
      "Beverages",
      "Desserts",
      "Snacks",
      "Chaat",
      "Street Food",
      "Chinese",
      "Bakery",
      "North Indian",
      "South Indian",
    ],
    avgRating: 4.4,
    veg: true,
    parentId: "7052",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    deliverytime: "30",
  },
  {
    id: "101060",
    name: "Manohar Dairy and Restaurant",
    cloudinaryImageId: "rsk6jwh8iwou7sstdsdy",
    locality: "Hamidia Road",
    areaName: "Hamidia Road",
    costForTwo: "₹300 for two",
    cuisines: [
      "Sweets",
      "Beverages",
      "Desserts",
      "Snacks",
      "Chaat",
      "Street Food",
      "Chinese",
      "Bakery",
      "North Indian",
      "South Indian",
    ],
    avgRating: 4.4,
    veg: true,
    parentId: "7052",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    deliverytime: "30",
  },
  {
    id: "101061",
    name: "Manohar Dairy and Restaurant",
    cloudinaryImageId: "yhnrql8wxgu8sgqjczos",
    locality: "Hamidia Road",
    areaName: "Hamidia Road",
    costForTwo: "₹300 for two",
    cuisines: [
      "Sweets",
      "Beverages",
      "Desserts",
      "Snacks",
      "Chaat",
      "Street Food",
      "Chinese",
      "Bakery",
      "North Indian",
      "South Indian",
    ],
    avgRating: 4.4,
    veg: true,
    parentId: "7052",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    deliverytime: "30",
  },
  {
    id: "101062",
    name: "Manohar Dairy and Restaurant",
    cloudinaryImageId: "yhnrql8wxgu8sgqjczos",
    locality: "Hamidia Road",
    areaName: "Hamidia Road",
    costForTwo: "₹300 for two",
    cuisines: [
      "Sweets",
      "Beverages",
      "Desserts",
      "Snacks",
      "Chaat",
      "Street Food",
      "Chinese",
      "Bakery",
      "North Indian",
      "South Indian",
    ],
    avgRating: 4.4,
    veg: true,
    parentId: "7052",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    deliverytime: "30",
  },
  {
    id: "101063",
    name: "Manohar Dairy and Restaurant",
    cloudinaryImageId: "yhnrql8wxgu8sgqjczos",
    locality: "Hamidia Road",
    areaName: "Hamidia Road",
    costForTwo: "₹300 for two",
    cuisines: [
      "Sweets",
      "Beverages",
      "Desserts",
      "Snacks",
      "Chaat",
      "Street Food",
      "Chinese",
      "Bakery",
      "North Indian",
      "South Indian",
    ],
    avgRating: 4.4,
    veg: true,
    parentId: "7052",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    deliverytime: "30",
  },
  {
    id: "101064",
    name: "Manohar Dairy and Restaurant",
    cloudinaryImageId: "yhnrql8wxgu8sgqjczos",
    locality: "Hamidia Road",
    areaName: "Hamidia Road",
    costForTwo: "₹300 for two",
    cuisines: [
      "Sweets",
      "Beverages",
      "Desserts",
      "Snacks",
      "Chaat",
      "Street Food",
      "Chinese",
      "Bakery",
      "North Indian",
      "South Indian",
    ],
    avgRating: 4.4,
    veg: true,
    parentId: "7052",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    deliverytime: "30",
  },
  {
    id: "101065",
    name: "Manohar Dairy and Restaurant",
    cloudinaryImageId: "yhnrql8wxgu8sgqjczos",
    locality: "Hamidia Road",
    areaName: "Hamidia Road",
    costForTwo: "₹300 for two",
    cuisines: [
      "Sweets",
      "Beverages",
      "Desserts",
      "Snacks",
      "Chaat",
      "Street Food",
      "Chinese",
      "Bakery",
      "North Indian",
      "South Indian",
    ],
    avgRating: 4.4,
    veg: true,
    parentId: "7052",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    deliverytime: "30",
  },
  {
    id: "101066",
    name: "Manohar Dairy and Restaurant",
    cloudinaryImageId: "yhnrql8wxgu8sgqjczos",
    locality: "Hamidia Road",
    areaName: "Hamidia Road",
    costForTwo: "₹300 for two",
    cuisines: [
      "Sweets",
      "Beverages",
      "Desserts",
      "Snacks",
      "Chaat",
      "Street Food",
      "Chinese",
      "Bakery",
      "North Indian",
      "South Indian",
    ],
    avgRating: 4.4,
    veg: true,
    parentId: "7052",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    deliverytime: "30",
  },
  {
    id: "101067",
    name: "Manohar Dairy and Restaurant",
    cloudinaryImageId: "yhnrql8wxgu8sgqjczos",
    locality: "Hamidia Road",
    areaName: "Hamidia Road",
    costForTwo: "₹300 for two",
    cuisines: [
      "Sweets",
      "Beverages",
      "Desserts",
      "Snacks",
      "Chaat",
      "Street Food",
      "Chinese",
      "Bakery",
      "North Indian",
      "South Indian",
    ],
    avgRating: 4.4,
    veg: true,
    parentId: "7052",
    avgRatingString: "4.4",
    totalRatingsString: "10K+",
    deliverytime: "30",
  },
];

export default resList;
